// export const savedPokemons = [
//   {
//     cardName: 'Bulbasaur',
//     cardDescription: 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.',
//     cardAttr1: '23',
//     cardAttr2: '15',
//     cardAttr3: '20',
//     cardImage: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
//     cardRare: 'normal',
//     cardState: [],
//     pokemonType: 'Planta',
//     pokemonTypeTwo: 'Venenoso',
//     nameFilter: '',
//     rareFilter: '',
//     trunfoFilter: false,
//     cardTrunfo: false,
//     hasTrunfo: false,
//     isSaveButtonDisabled: false,
//     cardNameValidation: true,
//     cardDescriptionValidation: true,
//     cardImageValidation: true,
//   },
//   {
//     "cardName": "Charmander",
//     "cardDescription": "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
//     "cardAttr1": "30",
//     "cardAttr2": "10",
//     "cardAttr3": "20",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
//     "cardRare": "normal",
//     "cardState": [
//     ],
//     "pokemonType": "Fogo",
//     "pokemonTypeTwo": "",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": false,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     "cardDescriptionValidation": true,
//     "cardImageValidation": true
//   },
//   {
//     "cardName": "Squirtle",
//     "cardDescription": "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
//     "cardAttr1": "20",
//     "cardAttr2": "25",
//     "cardAttr3": "20",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
//     "cardRare": "normal",
//     "cardState": [],
//     "pokemonType": "Água",
//     "pokemonTypeTwo": "",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": false,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     "cardDescriptionValidation": true,
//     "cardImageValidation": true
//   },
//   {
//     "cardName": "Charizard",
//     "cardDescription": "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.",
//     "cardAttr1": "50",
//     "cardAttr2": "40",
//     "cardAttr3": "60",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
//     "cardRare": "muito raro",
//     "cardState": [],
//     "pokemonType": "Fogo",
//     "pokemonTypeTwo": "Voador",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": false,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     "cardDescriptionValidation": true,
//     "cardImageValidation": true
//   },
//   {
//     "cardName": "Venusaur ",
//     "cardDescription": "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
//     "cardAttr1": "40",
//     "cardAttr2": "30",
//     "cardAttr3": "50",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
//     "cardRare": "muito raro",
//     "cardState": [],
//     "pokemonType": "Planta",
//     "pokemonTypeTwo": "Venenoso",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": false,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     "cardDescriptionValidation": true,
//     "cardImageValidation": true
//   },
//   {
//     "cardName": "Blastoise",
//     "cardDescription": "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.",
//     "cardAttr1": "40",
//     "cardAttr2": "60",
//     "cardAttr3": "40",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
//     "cardRare": "muito raro",
//     "cardState": [],
//     "pokemonType": "Água",
//     "pokemonTypeTwo": "",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": false,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     "cardDescriptionValidation": true,
//     "cardImageValidation": true
//   },
//   {
//     "cardName": "Pikachu",
//     "cardDescription": "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
//     "cardAttr1": "35",
//     "cardAttr2": "30",
//     "cardAttr3": "35",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
//     "cardRare": "raro",
//     "cardState": [],
//     "pokemonType": "Elétrico",
//     "pokemonTypeTwo": "",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": false,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     "cardDescriptionValidation": true,
//     "cardImageValidation": true
//   },
//   {
//     "cardName": "Zapdos",
//     "cardDescription": "Zapdos is a legendary bird Pokémon. It’s said that when Zapdos rubs its feathers together, lightning will fall immediately after.",
//     "cardAttr1": "60",
//     "cardAttr2": "65",
//     "cardAttr3": "70",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png",
//     "cardRare": "lendário",
//     "cardState": [],
//     "pokemonType": "Elétrico",
//     "pokemonTypeTwo": "Voador",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": false,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     "cardDescriptionValidation": true,
//     "cardImageValidation": true
//   },
//   {
//     "cardName": "Rayquaza",
//     "cardDescription": "Rayquaza is said to have lived for hundreds of millions of years. Legends remain of how it put to rest the clash between Kyogre and Groudon.",
//     "cardAttr1": "75",
//     "cardAttr2": "65",
//     "cardAttr3": "70",
//     "cardImage": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/384.png",
//     "cardRare": "lendário",
//     "cardState": [],
//     "pokemonType": "Dragão",
//     "pokemonTypeTwo": "Voador",
//     "nameFilter": "",
//     "rareFilter": "",
//     "trunfoFilter": false,
//     "cardTrunfo": true,
//     "hasTrunfo": false,
//     "isSaveButtonDisabled": false,
//     "cardNameValidation": true,
//     'cardDescriptionValidation': true,
//     'cardImageValidation': true
//   },
// ];
